# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fe7df138a0bd14933915c899bb7bdce88d0746b098d386ea6123eb9b7eab66a45de060206f635d4bab0e3994122412bfc2a7a8282509d3a590a83ed6f6e14050

test:
  secret_key_base: 48d8c4b525f2eb25e9b6a9c7f1c92354d8a22d803dcb7c136445054ea54958f83924d0fd17e65f8637e8546ddb25b3672000ab1f20bf4436cef2a2e12a1d868e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
